apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1}}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      dnsConfig:
        nameservers:
          - 1.1.1.1
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - hostPath:
            path: /dev/mem
            type: ""
          name: dev-mem
      containers:
      {{/*   TODO: Release.Name     */}}
        - name: {{ .Chart.Name }}
{{/*      TODO:    #  ekasyan/kbot.git/helm:v1.0.1-b82a815-amd64 */}}
          image: "{{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Values.image.tag }}-{{ .Values.image.arch | default "amd64"}}"
          volumeMounts:
            - mountPath: /dev/mem
              name: dev-mem
          env:
            - name: {{ .Values.secret.name }}
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.secret.tokenKey }}
                  name: {{ .Values.secret.tokenName }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
