# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ekasyan
  tag: "v1.0.4-47c6f54-7cbdc75-ce55add"
  arch: amd64

secret:
  name: TELE_TOKEN
  tokenName: token
  tokenKey: TELE_TOKEN